spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  application:
    name: lftapi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    timeout: 2592000
    # todo 取消注释开启分布式 session（须先配置 Redis）
    #store-type: redis
    # 30 天过期

  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartbi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: lft13658349581

  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000

  redisson:
    database: 2
    host: localhost
    port: 6379


  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

server:
  address: localhost
  port: 8080
  servlet:
    context-path: /smart-bi
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

yuapi:
  client:
    access-key: hrglxr6jo838hd1vzwzcbj1mmmjt8xu6
    secret-key: 7ql7nutarhb6lgcb6zfmussidi2vbwup
